module.exports = {
  "units": [
    {
      "name": "Aegis",
      "spell": false,
      "gold": 6,
      "energy": 0,
      "green": 3,
      "blue": 0,
      "red": 0,
      "supply": 10,
      "buildTime": 0,
      "health": 5,
      "frontline": false,
      "fragile": true,
      "blocker": true,
      "prompt": true,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Amporilla",
      "spell": false,
      "gold": 12,
      "energy": 0,
      "green": 0,
      "blue": 0,
      "red": 3,
      "supply": 4,
      "buildTime": 1,
      "health": 3,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Animus",
      "spell": false,
      "gold": 6,
      "energy": 0,
      "green": 0,
      "blue": 0,
      "red": 0,
      "supply": 10,
      "buildTime": 1,
      "health": 2,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Antima Comet",
      "spell": false,
      "gold": 2,
      "energy": 0,
      "green": 2,
      "blue": 1,
      "red": 0,
      "supply": 1,
      "buildTime": 2,
      "health": 1,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Apollo",
      "spell": false,
      "gold": 17,
      "energy": 0,
      "green": 0,
      "blue": 3,
      "red": 0,
      "supply": 4,
      "buildTime": 1,
      "health": 4,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Asteri Cannon",
      "spell": false,
      "gold": 16,
      "energy": 0,
      "green": 3,
      "blue": 0,
      "red": 0,
      "supply": 4,
      "buildTime": 1,
      "health": 9,
      "frontline": false,
      "fragile": true,
      "blocker": false,
      "prompt": false,
      "attack": 3,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Auric Impulse",
      "spell": false,
      "gold": 5,
      "energy": 0,
      "green": 0,
      "blue": 0,
      "red": 0,
      "supply": 20,
      "buildTime": 1,
      "health": 1,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Auride Core",
      "spell": false,
      "gold": 1,
      "energy": 0,
      "green": 0,
      "blue": 1,
      "red": 0,
      "supply": 4,
      "buildTime": 1,
      "health": 1,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    }
  ]
}
