"use strict"

module.exports = {
  "units": [
    {
      "name": "Aegis",
      "spell": false,
      "gold": 6,
      "energy": 0,
      "green": 3,
      "blue": 0,
      "red": 0,
      "supply": 10,
      "buildTime": 0,
      "health": 5,
      "frontline": false,
      "fragile": true,
      "blocker": true,
      "prompt": true,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Amporilla",
      "spell": false,
      "gold": 12,
      "energy": 0,
      "green": 0,
      "blue": 0,
      "red": 3,
      "supply": 4,
      "buildTime": 1,
      "health": 3,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Animus",
      "spell": false,
      "gold": 6,
      "energy": 0,
      "green": 0,
      "blue": 0,
      "red": 0,
      "supply": 10,
      "buildTime": 1,
      "health": 2,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Antima Comet",
      "spell": false,
      "gold": 2,
      "energy": 0,
      "green": 2,
      "blue": 1,
      "red": 0,
      "supply": 1,
      "buildTime": 2,
      "health": 1,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Apollo",
      "spell": false,
      "gold": 17,
      "energy": 0,
      "green": 0,
      "blue": 3,
      "red": 0,
      "supply": 4,
      "buildTime": 1,
      "health": 4,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Asteri Cannon",
      "spell": false,
      "gold": 16,
      "energy": 0,
      "green": 3,
      "blue": 0,
      "red": 0,
      "supply": 4,
      "buildTime": 1,
      "health": 9,
      "frontline": false,
      "fragile": true,
      "blocker": false,
      "prompt": false,
      "attack": 3,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Auric Impulse",
      "spell": false,
      "gold": 5,
      "energy": 0,
      "green": 0,
      "blue": 0,
      "red": 0,
      "supply": 20,
      "buildTime": 1,
      "health": 1,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Auride Core",
      "spell": false,
      "gold": 1,
      "energy": 0,
      "green": 0,
      "blue": 1,
      "red": 0,
      "supply": 4,
      "buildTime": 1,
      "health": 1,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Barrier",
      "spell": false,
      "gold": 1,
      "energy": 0,
      "green": 1,
      "blue": 0,
      "red": 0,
      "supply": 20,
      "buildTime": 0,
      "health": 1,
      "frontline": false,
      "fragile": false,
      "blocker": true,
      "prompt": true,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 1
    },
    {
      "name": "Blastforge",
      "spell": false,
      "gold": 5,
      "energy": 0,
      "green": 0,
      "blue": 0,
      "red": 0,
      "supply": 10,
      "buildTime": 1,
      "health": 3,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Blood Pact",
      "spell": true,
      "gold": 3,
      "energy": 0,
      "green": 0,
      "blue": 0,
      "red": 1,
      "supply": 10,
      "buildTime": 0,
      "health": 1,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Bloodrager",
      "spell": false,
      "gold": 7,
      "energy": 0,
      "green": 0,
      "blue": 0,
      "red": 1,
      "supply": 4,
      "buildTime": 1,
      "health": 2,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 2,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Cauterizer",
      "spell": false,
      "gold": 11,
      "energy": 0,
      "green": 0,
      "blue": 1,
      "red": 2,
      "supply": 4,
      "buildTime": 1,
      "health": 3,
      "frontline": false,
      "fragile": false,
      "blocker": true,
      "prompt": false,
      "attack": 2,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Centrifuge",
      "spell": false,
      "gold": 12,
      "energy": 3,
      "green": 0,
      "blue": 0,
      "red": 0,
      "supply": 1,
      "buildTime": 3,
      "health": 1,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Centurion",
      "spell": false,
      "gold": 18,
      "energy": 0,
      "green": 2,
      "blue": 2,
      "red": 1,
      "supply": 1,
      "buildTime": 0,
      "health": 6,
      "frontline": false,
      "fragile": false,
      "blocker": true,
      "prompt": true,
      "attack": 2,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Chieftain",
      "spell": false,
      "gold": 7,
      "energy": 0,
      "green": 2,
      "blue": 1,
      "red": 0,
      "supply": 10,
      "buildTime": 1,
      "health": 7,
      "frontline": false,
      "fragile": true,
      "blocker": true,
      "prompt": false,
      "attack": 2,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 3
    },
    {
      "name": "Chrono Filter",
      "spell": false,
      "gold": 4,
      "energy": 0,
      "green": 0,
      "blue": 0,
      "red": 0,
      "supply": 1,
      "buildTime": 1,
      "health": 2,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 2,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Cluster Bolt",
      "spell": true,
      "gold": 0,
      "energy": 0,
      "green": 4,
      "blue": 0,
      "red": 0,
      "supply": 10,
      "buildTime": 0,
      "health": 1,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Conduit",
      "spell": false,
      "gold": 4,
      "energy": 0,
      "green": 0,
      "blue": 0,
      "red": 0,
      "supply": 10,
      "buildTime": 1,
      "health": 3,
      "frontline": false,
      "fragile": true,
      "blocker": false,
      "prompt": false,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Cryo Ray",
      "spell": false,
      "gold": 1,
      "energy": 0,
      "green": 1,
      "blue": 0,
      "red": 0,
      "supply": 10,
      "buildTime": 1,
      "health": 2,
      "frontline": false,
      "fragile": true,
      "blocker": false,
      "prompt": false,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Cynestra",
      "spell": false,
      "gold": 11,
      "energy": 0,
      "green": 3,
      "blue": 0,
      "red": 1,
      "supply": 4,
      "buildTime": 1,
      "health": 2,
      "frontline": false,
      "fragile": true,
      "blocker": false,
      "prompt": false,
      "attack": 3,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Deadeye Operative",
      "spell": false,
      "gold": 8,
      "energy": 0,
      "green": 0,
      "blue": 2,
      "red": 0,
      "supply": 4,
      "buildTime": 1,
      "health": 2,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 1,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Defense Grid",
      "spell": false,
      "gold": 16,
      "energy": 0,
      "green": 0,
      "blue": 3,
      "red": 0,
      "supply": 1,
      "buildTime": 1,
      "health": 7,
      "frontline": false,
      "fragile": false,
      "blocker": true,
      "prompt": false,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 7
    },
    {
      "name": "Doomed Drone",
      "spell": false,
      "gold": 2,
      "energy": 1,
      "green": 0,
      "blue": 0,
      "red": 0,
      "supply": 20,
      "buildTime": 1,
      "health": 1,
      "frontline": false,
      "fragile": false,
      "blocker": true,
      "prompt": false,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 3
    },
    {
      "name": "Doomed Mech",
      "spell": false,
      "gold": 8,
      "energy": 0,
      "green": 0,
      "blue": 2,
      "red": 0,
      "supply": 10,
      "buildTime": 1,
      "health": 5,
      "frontline": false,
      "fragile": false,
      "blocker": true,
      "prompt": false,
      "attack": 2,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 5
    },
    {
      "name": "Doomed Wall",
      "spell": false,
      "gold": 7,
      "energy": 0,
      "green": 0,
      "blue": 1,
      "red": 0,
      "supply": 10,
      "buildTime": 0,
      "health": 4,
      "frontline": false,
      "fragile": false,
      "blocker": true,
      "prompt": true,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 3
    },
    {
      "name": "Drake",
      "spell": false,
      "gold": 16,
      "energy": 0,
      "green": 0,
      "blue": 3,
      "red": 0,
      "supply": 4,
      "buildTime": 1,
      "health": 5,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 5,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Drone",
      "spell": false,
      "gold": 3,
      "energy": 1,
      "green": 0,
      "blue": 0,
      "red": 0,
      "supply": 20,
      "buildTime": 1,
      "health": 1,
      "frontline": false,
      "fragile": false,
      "blocker": true,
      "prompt": false,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Electrovore",
      "spell": false,
      "gold": 4,
      "energy": 0,
      "green": 0,
      "blue": 0,
      "red": 1,
      "supply": 10,
      "buildTime": 1,
      "health": 2,
      "frontline": false,
      "fragile": false,
      "blocker": true,
      "prompt": false,
      "attack": 1,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Energy Matrix",
      "spell": false,
      "gold": 9,
      "energy": 0,
      "green": 0,
      "blue": 2,
      "red": 0,
      "supply": 4,
      "buildTime": 1,
      "health": 5,
      "frontline": false,
      "fragile": false,
      "blocker": true,
      "prompt": true,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Engineer",
      "spell": false,
      "gold": 2,
      "energy": 0,
      "green": 0,
      "blue": 0,
      "red": 0,
      "supply": 20,
      "buildTime": 1,
      "health": 1,
      "frontline": false,
      "fragile": false,
      "blocker": true,
      "prompt": false,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Feral Warden",
      "spell": false,
      "gold": 5,
      "energy": 0,
      "green": 1,
      "blue": 0,
      "red": 1,
      "supply": 10,
      "buildTime": 1,
      "health": 3,
      "frontline": false,
      "fragile": true,
      "blocker": true,
      "prompt": true,
      "attack": 1,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Fission Turret",
      "spell": false,
      "gold": 4,
      "energy": 0,
      "green": 1,
      "blue": 0,
      "red": 0,
      "supply": 10,
      "buildTime": 1,
      "health": 1,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 1,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 4
    },
    {
      "name": "Flame Animus",
      "spell": false,
      "gold": 7,
      "energy": 0,
      "green": 0,
      "blue": 1,
      "red": 0,
      "supply": 4,
      "buildTime": 1,
      "health": 2,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 1,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Forcefield",
      "spell": false,
      "gold": 1,
      "energy": 0,
      "green": 1,
      "blue": 0,
      "red": 0,
      "supply": 20,
      "buildTime": 0,
      "health": 2,
      "frontline": false,
      "fragile": true,
      "blocker": true,
      "prompt": true,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Frost Brooder",
      "spell": false,
      "gold": 5,
      "energy": 0,
      "green": 0,
      "blue": 0,
      "red": 2,
      "supply": 4,
      "buildTime": 1,
      "health": 2,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 9
    },
    {
      "name": "Frostbite",
      "spell": false,
      "gold": 2,
      "energy": 0,
      "green": 0,
      "blue": 0,
      "red": 1,
      "supply": 20,
      "buildTime": 1,
      "health": 1,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Gauss Cannon",
      "spell": false,
      "gold": 6,
      "energy": 0,
      "green": 1,
      "blue": 0,
      "red": 0,
      "supply": 10,
      "buildTime": 1,
      "health": 5,
      "frontline": false,
      "fragile": true,
      "blocker": false,
      "prompt": false,
      "attack": 1,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Gauss Charge",
      "spell": false,
      "gold": 1,
      "energy": 0,
      "green": 1,
      "blue": 0,
      "red": 0,
      "supply": 20,
      "buildTime": 1,
      "health": 1,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 1,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Gauss Fabricator",
      "spell": false,
      "gold": 13,
      "energy": 0,
      "green": 4,
      "blue": 0,
      "red": 0,
      "supply": 1,
      "buildTime": 1,
      "health": 13,
      "frontline": false,
      "fragile": true,
      "blocker": false,
      "prompt": false,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 8
    },
    {
      "name": "Gaussite Symbiote",
      "spell": false,
      "gold": 7,
      "energy": 0,
      "green": 0,
      "blue": 0,
      "red": 2,
      "supply": 4,
      "buildTime": 1,
      "health": 2,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 1,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Grenade Mech",
      "spell": false,
      "gold": 10,
      "energy": 0,
      "green": 0,
      "blue": 2,
      "red": 2,
      "supply": 10,
      "buildTime": 1,
      "health": 4,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 1,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Grimbotch",
      "spell": false,
      "gold": 4,
      "energy": 0,
      "green": 0,
      "blue": 0,
      "red": 1,
      "supply": 10,
      "buildTime": 1,
      "health": 2,
      "frontline": false,
      "fragile": false,
      "blocker": true,
      "prompt": false,
      "attack": 1,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 4
    },
    {
      "name": "Hannibull",
      "spell": false,
      "gold": 9,
      "energy": 0,
      "green": 0,
      "blue": 1,
      "red": 1,
      "supply": 4,
      "buildTime": 1,
      "health": 6,
      "frontline": true,
      "fragile": false,
      "blocker": true,
      "prompt": false,
      "attack": 2,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Hellhound",
      "spell": false,
      "gold": 5,
      "energy": 0,
      "green": 0,
      "blue": 1,
      "red": 1,
      "supply": 10,
      "buildTime": 1,
      "health": 1,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 1,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Husk",
      "spell": false,
      "gold": 2,
      "energy": 0,
      "green": 0,
      "blue": 0,
      "red": 1,
      "supply": 20,
      "buildTime": 0,
      "health": 1,
      "frontline": false,
      "fragile": false,
      "blocker": true,
      "prompt": true,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Iceblade Golem",
      "spell": false,
      "gold": 7,
      "energy": 0,
      "green": 0,
      "blue": 1,
      "red": 1,
      "supply": 10,
      "buildTime": 1,
      "health": 6,
      "frontline": true,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 1,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Immolite",
      "spell": false,
      "gold": 3,
      "energy": 0,
      "green": 0,
      "blue": 0,
      "red": 1,
      "supply": 20,
      "buildTime": 1,
      "health": 1,
      "frontline": false,
      "fragile": false,
      "blocker": true,
      "prompt": false,
      "attack": 1,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 2,
      "lifespan": 0
    },
    {
      "name": "Iso Kronus",
      "spell": false,
      "gold": 5,
      "energy": 0,
      "green": 1,
      "blue": 0,
      "red": 0,
      "supply": 10,
      "buildTime": 2,
      "health": 1,
      "frontline": false,
      "fragile": true,
      "blocker": false,
      "prompt": false,
      "attack": 2,
      "stamina": 0,
      "exhaustAfterTurn": 2,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Lucina Spinos",
      "spell": false,
      "gold": 18,
      "energy": 0,
      "green": 0,
      "blue": 0,
      "red": 4,
      "supply": 1,
      "buildTime": 1,
      "health": 1,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 4,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Militia",
      "spell": false,
      "gold": 6,
      "energy": 0,
      "green": 0,
      "blue": 1,
      "red": 0,
      "supply": 10,
      "buildTime": 1,
      "health": 2,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 1,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Odin",
      "spell": false,
      "gold": 21,
      "energy": 0,
      "green": 0,
      "blue": 3,
      "red": 0,
      "supply": 1,
      "buildTime": 1,
      "health": 5,
      "frontline": false,
      "fragile": false,
      "blocker": true,
      "prompt": false,
      "attack": 4,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Omega Splitter",
      "spell": false,
      "gold": 14,
      "energy": 0,
      "green": 0,
      "blue": 3,
      "red": 0,
      "supply": 4,
      "buildTime": 1,
      "health": 6,
      "frontline": false,
      "fragile": false,
      "blocker": true,
      "prompt": false,
      "attack": 3,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Ossified Drone",
      "spell": false,
      "gold": 5,
      "energy": 1,
      "green": 0,
      "blue": 0,
      "red": 1,
      "supply": 1,
      "buildTime": 1,
      "health": 2,
      "frontline": false,
      "fragile": false,
      "blocker": true,
      "prompt": false,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Perforator",
      "spell": false,
      "gold": 3,
      "energy": 0,
      "green": 0,
      "blue": 0,
      "red": 1,
      "supply": 10,
      "buildTime": 1,
      "health": 2,
      "frontline": false,
      "fragile": false,
      "blocker": true,
      "prompt": false,
      "attack": 1,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Pixie",
      "spell": false,
      "gold": 1,
      "energy": 0,
      "green": 0,
      "blue": 1,
      "red": 0,
      "supply": 20,
      "buildTime": 1,
      "health": 1,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 1,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Plasmafier",
      "spell": false,
      "gold": 12,
      "energy": 0,
      "green": 3,
      "blue": 1,
      "red": 0,
      "supply": 4,
      "buildTime": 1,
      "health": 4,
      "frontline": false,
      "fragile": true,
      "blocker": true,
      "prompt": false,
      "attack": 4,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Plexo Cell",
      "spell": false,
      "gold": 2,
      "energy": 0,
      "green": 2,
      "blue": 0,
      "red": 0,
      "supply": 10,
      "buildTime": 0,
      "health": 4,
      "frontline": false,
      "fragile": false,
      "blocker": true,
      "prompt": true,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 1
    },
    {
      "name": "Polywall",
      "spell": false,
      "gold": 10,
      "energy": 0,
      "green": 0,
      "blue": 1,
      "red": 0,
      "supply": 10,
      "buildTime": 0,
      "health": 6,
      "frontline": true,
      "fragile": false,
      "blocker": true,
      "prompt": true,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Protoplasm",
      "spell": false,
      "gold": 7,
      "energy": 0,
      "green": 2,
      "blue": 0,
      "red": 2,
      "supply": 10,
      "buildTime": 0,
      "health": 4,
      "frontline": false,
      "fragile": true,
      "blocker": true,
      "prompt": true,
      "attack": 4,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Rhino",
      "spell": false,
      "gold": 5,
      "energy": 0,
      "green": 0,
      "blue": 0,
      "red": 1,
      "supply": 10,
      "buildTime": 0,
      "health": 2,
      "frontline": false,
      "fragile": false,
      "blocker": true,
      "prompt": true,
      "attack": 1,
      "stamina": 2,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Scorchilla",
      "spell": false,
      "gold": 7,
      "energy": 0,
      "green": 1,
      "blue": 0,
      "red": 1,
      "supply": 10,
      "buildTime": 1,
      "health": 3,
      "frontline": false,
      "fragile": true,
      "blocker": true,
      "prompt": false,
      "attack": 3,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 3,
      "lifespan": 0
    },
    {
      "name": "Sentinel",
      "spell": false,
      "gold": 8,
      "energy": 0,
      "green": 1,
      "blue": 0,
      "red": 1,
      "supply": 10,
      "buildTime": 1,
      "health": 4,
      "frontline": false,
      "fragile": true,
      "blocker": true,
      "prompt": false,
      "attack": 1,
      "stamina": 4,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Shadowfang",
      "spell": false,
      "gold": 7,
      "energy": 0,
      "green": 0,
      "blue": 0,
      "red": 3,
      "supply": 10,
      "buildTime": 1,
      "health": 1,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 2,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Shiver Yeti",
      "spell": false,
      "gold": 5,
      "energy": 0,
      "green": 0,
      "blue": 0,
      "red": 1,
      "supply": 10,
      "buildTime": 0,
      "health": 2,
      "frontline": false,
      "fragile": false,
      "blocker": true,
      "prompt": true,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Shredder",
      "spell": false,
      "gold": 5,
      "energy": 0,
      "green": 0,
      "blue": 1,
      "red": 0,
      "supply": 10,
      "buildTime": 1,
      "health": 4,
      "frontline": true,
      "fragile": false,
      "blocker": true,
      "prompt": false,
      "attack": 1,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Steelforge",
      "spell": false,
      "gold": 3,
      "energy": 0,
      "green": 0,
      "blue": 0,
      "red": 0,
      "supply": 4,
      "buildTime": 1,
      "health": 4,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Steelsplitter",
      "spell": false,
      "gold": 6,
      "energy": 0,
      "green": 0,
      "blue": 1,
      "red": 0,
      "supply": 10,
      "buildTime": 1,
      "health": 3,
      "frontline": false,
      "fragile": false,
      "blocker": true,
      "prompt": false,
      "attack": 1,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Synthesizer",
      "spell": false,
      "gold": 6,
      "energy": 0,
      "green": 0,
      "blue": 1,
      "red": 0,
      "supply": 4,
      "buildTime": 1,
      "health": 4,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Tarsier",
      "spell": false,
      "gold": 4,
      "energy": 0,
      "green": 0,
      "blue": 0,
      "red": 1,
      "supply": 10,
      "buildTime": 2,
      "health": 1,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 1,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Tatsu Nullifier",
      "spell": false,
      "gold": 11,
      "energy": 0,
      "green": 0,
      "blue": 0,
      "red": 4,
      "supply": 4,
      "buildTime": 1,
      "health": 2,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 2,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Tesla Coil",
      "spell": false,
      "gold": 10,
      "energy": 0,
      "green": 2,
      "blue": 1,
      "red": 0,
      "supply": 4,
      "buildTime": 1,
      "health": 3,
      "frontline": false,
      "fragile": true,
      "blocker": false,
      "prompt": false,
      "attack": 3,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Thermite Core",
      "spell": false,
      "gold": 1,
      "energy": 0,
      "green": 0,
      "blue": 1,
      "red": 0,
      "supply": 4,
      "buildTime": 1,
      "health": 1,
      "frontline": false,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 7
    },
    {
      "name": "Tia Thurnax",
      "spell": false,
      "gold": 4,
      "energy": 0,
      "green": 3,
      "blue": 0,
      "red": 1,
      "supply": 1,
      "buildTime": 0,
      "health": 4,
      "frontline": false,
      "fragile": true,
      "blocker": true,
      "prompt": true,
      "attack": 7,
      "stamina": 3,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Trinity Drone",
      "spell": false,
      "gold": 2,
      "energy": 1,
      "green": 1,
      "blue": 0,
      "red": 0,
      "supply": 10,
      "buildTime": 1,
      "health": 5,
      "frontline": false,
      "fragile": true,
      "blocker": false,
      "prompt": false,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Venge Cannon",
      "spell": false,
      "gold": 3,
      "energy": 0,
      "green": 3,
      "blue": 0,
      "red": 0,
      "supply": 10,
      "buildTime": 1,
      "health": 8,
      "frontline": false,
      "fragile": true,
      "blocker": false,
      "prompt": false,
      "attack": 2,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Vivid Drone",
      "spell": false,
      "gold": 4,
      "energy": 3,
      "green": 0,
      "blue": 0,
      "red": 0,
      "supply": 4,
      "buildTime": 1,
      "health": 1,
      "frontline": false,
      "fragile": false,
      "blocker": true,
      "prompt": false,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Wall",
      "spell": false,
      "gold": 5,
      "energy": 0,
      "green": 0,
      "blue": 1,
      "red": 0,
      "supply": 10,
      "buildTime": 1,
      "health": 3,
      "frontline": false,
      "fragile": false,
      "blocker": true,
      "prompt": true,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Wild Drone",
      "spell": false,
      "gold": 5,
      "energy": 2,
      "green": 0,
      "blue": 0,
      "red": 0,
      "supply": 10,
      "buildTime": 1,
      "health": 3,
      "frontline": true,
      "fragile": false,
      "blocker": false,
      "prompt": false,
      "attack": 0,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Xeno Guardian",
      "spell": false,
      "gold": 7,
      "energy": 0,
      "green": 1,
      "blue": 1,
      "red": 0,
      "supply": 10,
      "buildTime": 1,
      "health": 4,
      "frontline": false,
      "fragile": false,
      "blocker": true,
      "prompt": false,
      "attack": 1,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    },
    {
      "name": "Zemora Voidbringer",
      "spell": false,
      "gold": 6,
      "energy": 0,
      "green": 2,
      "blue": 0,
      "red": 0,
      "supply": 1,
      "buildTime": 6,
      "health": 20,
      "frontline": false,
      "fragile": true,
      "blocker": false,
      "prompt": false,
      "attack": 8,
      "stamina": 0,
      "exhaustAfterTurn": 0,
      "exhaustAfterClick": 0,
      "lifespan": 0
    }
  ]
}
